version: '3'

networks:
  local:

services:
  postgres:
    container_name: postgres_container
    image: postgres:10.12
    environment:
      POSTGRES_USER: UserLocal
      POSTGRES_PASSWORD: UserLocal
      POSTGRES_DB: LocalDB
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      local:
  fakemail:
    container_name: fakemail_container
    image: python:3.7-slim-buster
    ports:
      - 1025:1025
    restart: unless-stopped
    networks:
      local:
    command: "python -m smtpd -n -c DebuggingServer 0.0.0.0:1025"

  z1socialideas:
    container_name: django_container
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - pipenv_dev=1
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PIPENV_DOTENV_LOCATION=/tmp/.env
    working_dir: /code
    depends_on:
      - "postgres"
      - "fakemail"
    links:
      - postgres:postgres_container
      - fakemail:fakemail_container
    volumes:
      - ./z1socialideas:/code
      - ./.env:/tmp/.env
    ports:
      - 8000:8000
    networks:
      local:
    command: bash -c "
      dockerize -wait tcp://postgres_container:5432 -timeout 1m &&
      pipenv run python manage.py migrate &&
      pipenv run python manage.py loaddata socialuser/fixtures/initial_data.json &&
      pipenv run python manage.py runserver 0.0.0.0:8000
      "
